/*
Project "Electronic schematic and pcb CAD"
Copyright (c) 2026 Alexander Sibilev

SPDX-License-Identifier: GPL-3.0-or-later

Author
  Alexander Sibilev S.

Web
  www.SalixEDA.org

Description
  The SdAiGateway class handles asynchronous, non-blocking communication with
  OpenAI-compatible AI APIs (including local Ollama instances) within a dedicated worker thread.
  It processes streaming text responses via Server-Sent Events (SSE), parsing the raw HTTP data chunks on the fly.
  Each network request increments a unique transaction identifier, allowing the UI layer
  to correctly route incoming text fragments even during rapid user interactions or cancellation scenarios.
  It supports live generation cancellation via a dedicated abort slot and reads server settings
  seamlessly from the application configuration.
*/
#ifndef SDAIGATEWAY_H
#define SDAIGATEWAY_H

#include <QObject>
#include <QStringList>
#include <QNetworkAccessManager>
#include <QNetworkReply>

/// \brief Gateway for asynchronous communication with OpenAI-compatible APIs using streaming.
class SdAiGateway : public QObject {
    Q_OBJECT

    QNetworkAccessManager *mManager = nullptr;      //!< Network infrastructure manager.
    QNetworkReply         *mCurrentReply = nullptr; //!< Pointer to the active network response stream.
    QString                mBuffer;                 //!< Buffer used to accumulate split SSE data packets.
    int                    mCurrentId = 0;          //!< Monotonically increasing identifier for requests.


    //!
    //! \brief SdAiGateway  Constructor initializing the network access manager.
    //! \param parent       Parent object in application object hierarhy
    //!
    explicit SdAiGateway(QObject *parent = nullptr);
  public:

    /// \brief Destructor ensuring safe termination of any active network requests.
    ~SdAiGateway();

    //!
    //! \brief instance Returns the singleton instance of the gateway, initializing it and its worker thread.
    //! \return         Singleton instance of the gateway
    //!
    static SdAiGateway *instance();

  public slots:
    //!
    //! \brief question Submits a multi-turn dialog context to the selected AI model.
    //! \param system   The system prompt defining the agent's behavior and context.
    //! \param dialog   The history of the conversation (even index = user, odd index = AI).
    //!
    void question(const QString &system, const QStringList &dialog);

    void userQuestion( const QStringList &dialog );

    //!
    //! \brief cancel Aborts the current AI generation request immediately.
    //!
    void cancel();

  signals:
    //!
    //! \brief answer Emitted when a new token or text fragment is received from the API stream.
    //! \param id     The unique identifier of the transaction this fragment belongs to.
    //! \param text   The text chunk generated by the model (or empty on completion/error).
    //!
    void answer(int id, const QString &text);

  private slots:
    //!
    //! \brief onReadyRead Internal slot triggered when new raw data is available on the network socket.
    //!
    void onReadyRead();

    //!
    //! \brief onFinished Internal slot triggered when the HTTP request finishes execution.
    //!
    void onFinished();

    //!
    //! \brief onError Internal slot triggered when a network or HTTP protocol error occurs.
    //! \param code    The error code returned by the network subsystem.
    //!
    void onError(QNetworkReply::NetworkError code);
  };

#endif // SDAIGATEWAY_H
